In [1]:
import pandas as pd
pk=pd.read_csv("pokemon.csv",squeeze=True,)#usecols=["Pokemon"])

In [2]:
pk.head()

      Pokemon   Type
0   Bulbasaur  Grass
1     Ivysaur  Grass
2    Venusaur  Grass
3  Charmander   Fire
4  Charmeleon   Fire

In [23]:
pk.head(60)

       Pokemon      Type
0    Bulbasaur     Grass
1      Ivysaur     Grass
2     Venusaur     Grass
3   Charmander      Fire
4   Charmeleon      Fire
5    Charizard      Fire
6     Squirtle     Water
7    Wartortle     Water
8    Blastoise     Water
9     Caterpie       Bug
10     Metapod       Bug
11  Butterfree       Bug
12      Weedle       Bug
13      Kakuna       Bug
14    Beedrill       Bug
15      Pidgey    Normal
16   Pidgeotto    Normal
17     Pidgeot    Normal
18     Rattata    Normal
19    Raticate    Normal
20     Spearow    Normal
21      Fearow    Normal
22       Ekans    Poison
23       Arbok    Poison
24     Pikachu  Electric
25      Raichu  Electric
26   Sandshrew    Ground
27   Sandslash    Ground
28     Nidoran    Poison
29    Nidorina    Poison
30   Nidoqueen    Poison
31    Nidoranâ™‚    Poison
32    Nidorino    Poison
33    Nidoking    Poison
34    Clefairy     Fairy
35    Clefable     Fairy
36      Vulpix      Fire
37   Ninetales      Fire
38  Jigglypuff    Normal
39  Wigglytuff    Normal
40       Zubat    Poison
41      Golbat    Poison
42      Oddish     Grass
43       Gloom     Grass
44   Vileplume     Grass
45       Paras       Bug
46    Parasect       Bug
47     Venonat       Bug
48    Venomoth       Bug
49     Diglett    Ground
50     Dugtrio    Ground
51      Meowth    Normal
52     Persian    Normal
53     Psyduck     Water
54     Golduck     Water
55      Mankey  Fighting
56    Primeape  Fighting
57   Growlithe      Fire
58    Arcanine      Fire
59     Poliwag     Water

In [25]:
pk.tail()
pk.tail(10)

       Pokemon     Type
711   Bergmite      Ice
712    Avalugg      Ice
713     Noibat   Flying
714    Noivern   Flying
715    Xerneas    Fairy
716    Yveltal     Dark
717    Zygarde   Dragon
718    Diancie     Rock
719      Hoopa  Psychic
720  Volcanion     Fire

In [28]:
pk.values

array([['Bulbasaur', 'Grass'],
       ['Ivysaur', 'Grass'],
       ['Venusaur', 'Grass'],
       ...,
       ['Diancie', 'Rock'],
       ['Hoopa', 'Psychic'],
       ['Volcanion', 'Fire']], dtype=object)

In [32]:
pk.index

RangeIndex(start=0, stop=721, step=1)

In [41]:
pk.size

1442

In [42]:
pk.ndim

2

In [7]:
pk.shape

(721, 2)