In [2]:
import pandas as pd 
bond=pd.read_csv("jamesbond.csv",index_col="Film")
bond.sort_index(inplace=True)
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [4]:
bond.sample()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [11]:
bond.sample(n=10)
bond.sample(frac=.43)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [18]:
bond.sample(n=3,axis=1)

,Director,Bond Actor Salary,Box Office
Film,,,
A View to a Kill,John Glen,9.1,275.2
Casino Royale,Martin Campbell,3.3,581.5
Casino Royale,Ken Hughes,NaN,315.0
Diamonds Are Forever,Guy Hamilton,5.8,442.5
Die Another Day,Lee Tamahori,17.9,465.4
Dr. No,Terence Young,0.6,448.8
For Your Eyes Only,John Glen,NaN,449.4
From Russia with Love,Terence Young,1.6,543.8
GoldenEye,Martin Campbell,5.1,518.5
Goldfinger,Guy Hamilton,3.2,820.4
Licence to Kill,John Glen,7.9,250.9
Live and Let Die,Guy Hamilton,NaN,460.3
Moonraker,Lewis Gilbert,NaN,535.0
Never Say Never Again,Irvin Kershner,NaN,380.0
Octopussy,John Glen,7.8,373.8
On Her Majesty's Secret Service,Peter R. Hunt,0.6,291.5
Quantum of Solace,Marc Forster,8.1,514.2
Skyfall,Sam Mendes,14.5,943.5
Spectre,Sam Mendes,NaN,726.7
The Living Daylights,John Glen,5.2,313.5
The Man with the Golden Gun,Guy Hamilton,NaN,334.0
The Spy Who Loved Me,Lewis Gilbert,NaN,533.0
The World Is Not Enough,Michael Apted,13.5,439.5
Thunderball,Terence Young,4.7,848.1
Tomorrow Never Dies,Roger Spottiswoode,10.0,463.2
You Only Live Twice,Lewis Gilbert,4.4,514.2